package com.example.doctour.domain.model

data class DoctorDetail(
    val id: String,
    val average_rating: String?,
    val num_reviews: String?,
    val specialties: List<SpecialitySerializerFields>?= emptyList(),
    val clinic: List<ClinicSerializerFields>,
    val doctor_experience: List<Experience>?= emptyList(),
    val doctor_certificates: List<Certificates>?= emptyList(),
    val doctor_education: List<Education>?= emptyList(),
    val doctor_specialization: List<Specialization>?= emptyList(),
    val is_deleted:Boolean,
    val created_at:String?,
    val updated_at:String?,
    val photo: String?,
    val full_name: String?,
    val experience: Int?,
    val instagram:String?,
    val price: Int?,
    val summary: String?,
    val phone: String?,
    val city: Int?,
    val category_services: List<Int>?= emptyList(),
)
