package com.example.doctour.preferences
object PreferencesKeys {
    const val ACCESS_TOKEN = "accessToken"
    const val REFRESH_TOKEN = "refreshToken"
    const val IS_AUTHENTICATED = "isAuthenticated"
    const val USER_ID = "userID"
    const val USERNAME = "username"
    const val PASSWORD = "password"
    const val USER_NUMBER = "userNumber"
    const val DOCTOUR_SHARED_PREFERENCES = "DoctourSharedPreferences"
    const val PREFERENCE_ON_BOARDING = "preference_onBoarding"
    const val BOARD = "board"
    const val PREFERENCE_PROFILE = "preference_profile"
    const val NAME ="name"
    const val PHONE ="phone"
    const val BIRTHDAY = "birthday"
    const val GENDER ="gender"
    const val ID_PROFILE = "idd_profffile"
    const val USER_PROFILE ="preference"
}
